name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0' # متوافق تماماً مع Zapp (Dart 2.19.2)

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.5 # الإصدار المطلوب لضمان التوافق مع SDK 2.19
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4 # متوافق مع Dart 2.19
  intl: ^0.18.1 # متوافق مع Dart 2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
